### ISSUE TITLE
Failing to build docker image : Error: Cannot find module 'semver'

### ISSUE THREAD

**Issue by arthurzenika** [koding/docker-base#8]
```
Step 16 : RUN npm install --global         coffee-script@$COFFEE_SCRIPT_VERSION         gulp
 ---> Running in 4f8634ad4919
module.js:471
    throw err;
    ^

Error: Cannot find module 'semver'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/unsupported.js:2:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
The command '/bin/sh -c npm install --global         coffee-script@$COFFEE_SCRIPT_VERSION         gulp' returned a non-zero code: 1
```

**Comment by szkl** [comment]
@arthurlogilab I didn't get this error message. Can you reproduce it?

**Comment by arthurzenika** [comment]
@szkl yep, I can still reproduce (even with --no-cache)

**Comment by szkl** [comment]
@arthurlogilab could you describe your environment? Can you make sure node and npm versions match the ones defined in the Dockerfile?

**Comment by arthurzenika** [comment]
I'm not sure how the node / npm versions can be different since I'm doing a docker build. The FROM is ubuntu:16.04 ... do you want me to check if there is something missing from my ubuntu:16.04 image ?

**Comment by szkl** [comment]
No. I just wanted to double check if an error occurred but didn't interrupt the process.

Can you run a container from the image ubuntu:16.04 and execute commands in Dockerfile yourself? See if you can still get the error.

**Comment by arthurzenika** [comment]
I'm sorry but that doesn't feel useful. I don't understand the difference with docker build.

**Comment by szkl** [comment]
We are trying to troubleshoot and find what's going wrong in your environment. I can't reproduce it. I need some more info than error message above to help.
